/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js.
// It is intentionally checked in so CI builds have the correct types.

